{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-minio-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argus-minio
    app.kubernetes.io/part-of: argus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
{{- end }}
