{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: argus-minio
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argus-minio
    app.kubernetes.io/part-of: argus
spec:
  selector:
    app: argus-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
  type: ClusterIP
{{- end }}
