{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: argus-postgresql
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: argus-postgresql
    app.kubernetes.io/part-of: argus
spec:
  selector:
    app: argus-postgresql
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432
  type: ClusterIP
{{- end }}
